outDir: "results/AEI" #"/sc/arion/projects/ad-omics/jack/editing/mynd-stim/AEI/"
# hard coed
refDir: "/sc/arion/projects/breen_lab/AEI/"

metadata: "test_samples.tsv"

# dataset variables
paired: True
stranded: False

